CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "BloodTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(5) NOT NULL,
    CONSTRAINT "PK_BloodTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Medications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Name" character varying(120) NOT NULL,
    "DosageDisplay" character varying(50),
    "Frequency" character varying(20),
    "TimeOfDay" character varying(5),
    "PillsRemaining" integer NOT NULL,
    "RefillDate" date,
    "Notes" character varying(1000),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Medications" PRIMARY KEY ("Id")
);

CREATE TABLE "RelationshipTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(60) NOT NULL,
    CONSTRAINT "PK_RelationshipTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "EmergencyCards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DateOfBirth" date,
    "Last4SSN" character varying(4),
    "BloodTypeId" integer,
    "InsuranceProvider" character varying(120),
    "InsurancePolicyNumber" character varying(80),
    CONSTRAINT "PK_EmergencyCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmergencyCards_BloodTypes_BloodTypeId" FOREIGN KEY ("BloodTypeId") REFERENCES "BloodTypes" ("Id")
);

CREATE TABLE "Doses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MedicationId" integer NOT NULL,
    "Date" date NOT NULL,
    "Time" character varying(5) NOT NULL,
    "Taken" boolean NOT NULL,
    "TakenAt" timestamp with time zone,
    CONSTRAINT "PK_Doses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doses_Medications_MedicationId" FOREIGN KEY ("MedicationId") REFERENCES "Medications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AuthorizedUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(120) NOT NULL,
    "RelationshipTypeId" integer NOT NULL,
    "Email" character varying(120),
    "Phone" character varying(40),
    "AddedOn" date NOT NULL,
    CONSTRAINT "PK_AuthorizedUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuthorizedUsers_RelationshipTypes_RelationshipTypeId" FOREIGN KEY ("RelationshipTypeId") REFERENCES "RelationshipTypes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AuthorizedUsers_RelationshipTypeId" ON "AuthorizedUsers" ("RelationshipTypeId");

CREATE UNIQUE INDEX "IX_Doses_MedicationId_Date_Time" ON "Doses" ("MedicationId", "Date", "Time");

CREATE INDEX "IX_EmergencyCards_BloodTypeId" ON "EmergencyCards" ("BloodTypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413221402_InitialCreate', '8.0.4');

COMMIT;

