// <auto-generated />
using System;
using MedTrackerScreensMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedTrackerScreensMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedTrackerScreensMVC.Models.AuthorizedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AddedOn")
                        .HasColumnType("date")
                        .HasColumnName("added_on");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
<<<<<<< HEAD
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");
=======
                        .HasColumnType("nvarchar(120)");
>>>>>>> parent of bc5b6a1 (..)

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
<<<<<<< HEAD
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type_id");
=======
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    b.HasKey("Id")
                        .HasName("pk_authorized_user");

                    b.HasIndex("RelationshipTypeId")
                        .HasDatabaseName("ix_authorized_user_relationship_type_id");

                    b.ToTable("authorized_user", (string)null);
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
<<<<<<< HEAD
                        .HasColumnType("character varying(5)")
                        .HasColumnName("name");
=======
                        .HasColumnType("nvarchar(5)");
>>>>>>> parent of bc5b6a1 (..)

                    b.HasKey("Id")
                        .HasName("pk_blood_type");

                    b.ToTable("blood_type", (string)null);
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("MedicationId")
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<bool>("Taken")
                        .HasColumnType("boolean")
                        .HasColumnName("taken");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");
=======
                        .HasColumnType("int");

                    b.Property<bool>("Taken")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("datetime2");
>>>>>>> parent of bc5b6a1 (..)

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(5)
<<<<<<< HEAD
                        .HasColumnType("character varying(5)")
                        .HasColumnName("time");
=======
                        .HasColumnType("nvarchar(5)");
>>>>>>> parent of bc5b6a1 (..)

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_dose");

                    b.HasIndex("MedicationId", "Date", "Time")
                        .IsUnique()
                        .HasDatabaseName("ix_dose_medication_id_date_time");

                    b.ToTable("dose", (string)null);
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.EmergencyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodTypeId")
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("blood_type_id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("InsurancePolicyNumber")
                        .HasMaxLength(80)
<<<<<<< HEAD
                        .HasColumnType("character varying(80)")
                        .HasColumnName("insurance_policy_number");

                    b.Property<string>("InsuranceProvider")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("insurance_provider");

                    b.Property<string>("Last4SSN")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("last4ssn");
=======
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("InsuranceProvider")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Last4SSN")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");
>>>>>>> parent of bc5b6a1 (..)

                    b.HasKey("Id")
                        .HasName("pk_emergency_card");

                    b.HasIndex("BloodTypeId")
                        .HasDatabaseName("ix_emergency_card_blood_type_id");

                    b.ToTable("emergency_card", (string)null);
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosageDisplay")
                        .HasMaxLength(50)
<<<<<<< HEAD
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dosage_display");

                    b.Property<string>("Frequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");
=======
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
>>>>>>> parent of bc5b6a1 (..)

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
<<<<<<< HEAD
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PillsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("pills_remaining");
=======
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PillsRemaining")
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    b.Property<DateOnly?>("RefillDate")
                        .HasColumnType("date")
                        .HasColumnName("refill_date");

                    b.Property<string>("TimeOfDay")
                        .HasMaxLength(5)
<<<<<<< HEAD
                        .HasColumnType("character varying(5)")
                        .HasColumnName("time_of_day");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");
=======
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
>>>>>>> parent of bc5b6a1 (..)

                    b.HasKey("Id")
                        .HasName("pk_medication");

                    b.ToTable("medication", (string)null);
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.RelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
                        .HasColumnType("integer")
                        .HasColumnName("id");
=======
                        .HasColumnType("int");
>>>>>>> parent of bc5b6a1 (..)

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
<<<<<<< HEAD
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");
=======
                        .HasColumnType("nvarchar(60)");
>>>>>>> parent of bc5b6a1 (..)

                    b.HasKey("Id")
                        .HasName("pk_relationship_type");

                    b.ToTable("relationship_type", (string)null);
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.AuthorizedUser", b =>
                {
                    b.HasOne("MedTrackerScreensMVC.Models.RelationshipType", "RelationshipType")
                        .WithMany()
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_authorized_user_relationship_type_relationship_type_id");

                    b.Navigation("RelationshipType");
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.Dose", b =>
                {
                    b.HasOne("MedTrackerScreensMVC.Models.Medication", "Medication")
                        .WithMany("Doses")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dose_medication_medication_id");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.EmergencyCard", b =>
                {
                    b.HasOne("MedTrackerScreensMVC.Models.BloodType", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeId")
                        .HasConstraintName("fk_emergency_card_blood_type_blood_type_id");

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("MedTrackerScreensMVC.Models.Medication", b =>
                {
                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
