name: Build and Deploy to Azure

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ASPNETCORE_CONTENTROOT: C:\home\site\wwwroot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore MedTrackerMVC.sln

      - name: Build
        run: dotnet build MedTrackerMVC.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish MedTrackerMVC.sln -c Release -o ./publish

      - name: Install EF Tools
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
